#!/bin/sh

start() {
    wpa_supplicant -D wext -iwlan0 -c/etc/wpa_supplicant.conf &
    udhcpc -iwlan0 &
}
stop() {
	echo "OK"
}
restart() {
	stop
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

