#!/bin/sh

start() {
    ifconfig wlan0 192.168.10.1 netmask 255.255.255.0 up
    hostapd -d /etc/hostapd.conf &
    udhcpd
}
stop() {
	echo "OK"
}
restart() {
	stop
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

